version: '3.3'

services:
  mysql-service:
    image: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=root
    ports:
    - 3306:3306
  springboot-microservice:
    build: .
    environment:
       PORT: 8080
       DB_HOST: mysql-service
       DB_PORT: 3306
       DB_USER: root
       DB_PASS: root
    ports:
     - 8081:8080


